Fix a bug causing ByteBuffer throws NoSuchMethodError
In Java 9, the following methods of java.nio.ByteBuffer return
ByteBuffer instead of Buffer:
* position
* limit
* flip
* clear
This change breaks the compatibility of the byte code.